### ISSUE TITLE
Little More Install Hints

### ISSUE THREAD

**Issue by ax3l** [daftaupe/munin-tor#11]
Hi @mweinelt,

thank you for the nice scripts!
Can you please provide a little install description besides the `pip` line for non-python folks?

I guess I simply install the `tor_.py` script into `/usr/share/munin/plugins` but where to place the two (helper) scripts `circuits_by_country.py` and `get_info.py`?

Do I need to take care with `cookie` authentication which user to run munin-node from in the config lines (as with [arm](https://www.atagar.com/arm/)) or do you recommend to hardlink/mount-bind the `control_auth_cookie` file again?

**Comment by mweinelt** [comment]
Thanks @ax3l, of course I'll clarify.

Note: this still has to be brought into some better form, this is just a quick and dirty set of instructions. Also this might not adhere to proper packaging standards, I am however not a packager, so correct me if this is plain wrong.

**Getting the code**
```
# cd /usr/share/
# git clone https://github.com/mweinelt/munin-tor.git
```

**Resolving dependencies**
```
# cd /usr/share/munin-tor
# pip install -r requirements.txt
```

**Include in munins repertoire**
```
# ln -s /usr/share/munin-tor/tor_.py /usr/share/munin/plugins/
```

From there on you can treat it as any other munin plugin you use. If you want to update, just `git pull` in `/usr/share/munin-tor`.

At last a word of warning: You will be cloning code directly from a git repository as root and noone can guarantee you it has been thoroughly vetted. While you would usually trust your distribution packaging system, this is not possible in this case.
So what I want to say: Before pulling random code from the Internet and executing it as root you might want to look through it first.

**Comment by ax3l** [comment]
Thank you for the hints!
You are indeed right, the first thing I did was checking your code ;)

I just found some minor additions that might be useful.

**On a Debian (minimal) system, install**
```
# apt-get install python-pip python-dev libgeoip-dev
```
to provide the `stem` and `GeoIP` dependencies used by `pip`.

**Cookie auth**

To enable cookie-based authentication, e.g. to read the file `/home/tor/.tor/control_auth_cookie`, I set in `/etc/munin/plugin-conf.d/[tor_ | munin-node]`
```
[tor_*]
user tor
group tor
```

I prefer that over the password auth, since files in `/etc/munin/plugin-conf.d/` are usually readable by all users and the steering of tor is not read-only. Fair enough: the dir itself should only be accessible by `root:munin` by default.

**Comment by micah** [comment]
Could the circuits_by_country.py and get_info.py be incorporated into the tor_.py, instead of having them be different files? 

The reason I ask is because munin plugins typically are just one file, and any dependencies are external. I use several hundred munin plugins, and this is the first one that breaks my configuration management method of deploying munin plugins. I have to special case this one to install it a new way.

By the way, it also isn't necessary to use pip to install the dependencies always. On a debian system, you can just apt-get install python-stem python-geoip and then be done.

**Comment by daftaupe** [comment]
@micah : if still interested, you can check https://github.com/daftaupe/munin-plugins-tor/tree/merge
I did my best to merge all files into one.

**Comment by daftaupe** [comment]
I'm closing this as the plugin has changed quite a lot recently, can be reopen if the instructions are still considered unclear.
