### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by daftaupe** [daftaupe/munin-tor#19]
Hello,

As i see you're not planning to maintain the repo anymore. Is it possible to get it transfered ? Maybe after i do a pull request from my fork ?
That would allow me to work on the issues opened.

Regards,

**Comment by mweinelt** [comment]
Totally, let's get this done.

**Comment by daftaupe** [comment]
Thanks :)

I opened PR #20 for this purpose.

**Comment by mweinelt** [comment]
What's the target account?

**Comment by daftaupe** [comment]
Well I guess mine, daftaupe, do you need something else ?

**Comment by mweinelt** [comment]
`daftaupe already has a repository in the mweinelt/munin-tor network
 Unwatch`

**Comment by daftaupe** [comment]
Ah, that's because i have to delete the fork first, wait a sec.

**Comment by mweinelt** [comment]
> Repository transfer to daftaupe requested

good to go!

**Comment by daftaupe** [comment]
Alright, it seems to be done now :)

Thanks a lot for your reactivity !
