### ISSUE TITLE
Units would be good

### ISSUE THREAD

**Issue by simonszu** [daftaupe/munin-tor#9]
Hi,

i installed your plugins yesterday on my relay server, and the work great, thank you. But i noticed: Some units on the y-axis would be helpful.
For example, the countries: I know that Canada has currently 123.89. But - 123.89 of what? Connections? Traffic?
And the traffic - i know that currently 5.46k are read. Do you mean inbound or outbound traffic? 5.46k of what? Bytes?
Maybe i'll look in the source myself, fix it and create a pull request, but i just wanted to create this issue first ;)

**Comment by ghost** [comment]
ACK. In what unit is the value of tor_traffic? E.g. Bit/s or Byte/s? Would be good to have the unit displayed. I found "bytes read/written" is hidden in the plugin "info", but to see that, You have first to click on the graph. To see it at once, as a workaround I overwrote the "graph_vlabel" with
```tor_traffic.graph_vlabel Byte/s``` in the host specific section on the munin server.

**Comment by daftaupe** [comment]
Hello @wodry I guess having the same label as https://github.com/munin-monitoring/contrib/blob/master/plugins/tor/example-graphs/tor_-1.png would work, wouldn't it ?

I've pushed something [there](https://github.com/daftaupe/munin-tor/tree/traffic_units) can you try and report please ?

**Comment by ghost** [comment]
untested ACK 84e3c62a51f0908640dad226f0e966c9dbd39a8d

**Comment by ghost** [comment]
Tested ACK 84e3c62a51f0908640dad226f0e966c9dbd39a8d

**Comment by daftaupe** [comment]
@wodry this has been merged in https://github.com/munin-monitoring/contrib/commit/168f6f924fc8efc2719af852977e8c2da5ffb0e0
I think this ticket can be closed.
